USE [BD_MantenimientoASP]
GO

/****** Object:  Table [dbo].[Usuario]    Script Date: 06/19/2013 01:11:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Usuario](
	[ID_USUARIO] [varchar](10) NOT NULL,
	[NOMBRE] [varchar](max) NULL,
	[CARGO] [varchar](50) NULL,
	[DEPARTAMENTO] [varchar](10) NULL,
	[USUARIO] [varchar](30) NULL,
	[CLAVE] [varchar](30) NULL,
	[PREGUNTA_SECRETA] [varchar](max) NULL,
	[RESPUESTA_SECRETA] [varchar](max) NULL,
	[EMAIL] [varchar](100) NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

